version: 0.2

phases:
  install:
    commands:
      - echo Running install phase
    finally:
      - echo Executing install phase finally
  pre_build:
    commands:
      - echo Running pre_build phase
    finally:
      - echo Executing pre_build phase finally
  build:
    commands:
      - echo Running build phase
    finally:
      - echo Executing build phase finally
  post_build:
    commands:
      - echo Running post_build phase
    finally:
      - echo Executing post_build phase